---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Home dashboard"
subtitle: "CCEU"
#logo: "logo.png"
icon: "fas fa-home"

header: true

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#4285f4"

# Optional message
message:
#url: https://b4bz.io
#style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#title: "Demo !"
#icon: "fa fa-grin"
#content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links: []

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Productivity"
    icon: "fas fa-star"
    items:
      - name: "Microsoft 365"
        logo: "assets/tools/ms_office.png"
        subtitle: "Office Online"
        tag: "office"
        url: "https://www.office.com/"
      - name: "Font Awesome"
        icon: "fab fa-font-awesome"
        subtitle: "Icon Gallery"
        tag: "icons"
        url: "https://fontawesome.com/icons?d=gallery&m=free"
      - name: "Confluence"
        logo: "assets/tools/confluence.svg"
        subtitle: "Collaborative Wiki"
        tag: "confluence"
        url: "https://code-crafting.atlassian.net/wiki/spaces"
      - name: "Jira"
        logo: "assets/tools/jira.png"
        subtitle: "Project Management"
        tag: "jira"
        url: "https://code-crafting.atlassian.net/"
  - name: "Server/Cloud Management"
    icon: "fas fa-server"
    items:
      - name: "GitHub CCEU Org"
        logo: "assets/tools/github.png"
        subtitle: "GitHub.com"
        tag: "git"
        url: "https://github.com/CCEU-code-crafting"
      - name: "Cloud MongoDB"
        logo: "assets/tools/mongodb.png"
        subtitle: "Atlas"
        tag: "database"
        url: "https://cloud.mongodb.com/"
      - name: "Nginx Proxy Manager"
        logo: "assets/tools/nginx_proxy_manager.png"
        subtitle: "Reverse Proxy"
        tag: "nginx"
        url: "https://nginx.code-crafting.eu/"
      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "Docker Container Management"
        tag: "docker"
        url: "https://portainer.code-crafting.eu/"
  - name: "CCEU code-crafting"
    icon: "fas fa-briefcase"
    items:
      - name: "lexoffice"
        logo: "assets/tools/lexoffice.png"
        subtitle: "Buchhaltung"
        tag: "desktop"
        url: "https://app.lexoffice.de/"
      - name: "Strato"
        logo: "assets/tools/strato.png"
        subtitle: "Kundenlogin"
        tag: "server"
        url: "https://www.strato.de/apps/CustomerService#/skl"
      - name: "IONOS"
        logo: "assets/tools/ionos.png"
        subtitle: "Domain & Mail"
        tag: "domain"
        url: "https://mein.ionos.de/"
      - name: "OVHcloud"
        logo: "assets/tools/ovh.svg"
        subtitle: "Domain & Mail"
        tag: "domain"
        url: "https://www.ovh.com/manager/#/"
      - name: "ADDISON OneClick"
        logo: "assets/tools/lkc.png"
        subtitle: "LKC Steuerberatung"
        tag: "steuer"
        url: "https://schroedinger-steuerberater.portal-bereich.de/html/#"
  - name: "Media & Leisure"
    icon: "fab fa-youtube"
    items:
      - name: "YouTube"
        logo: "assets/tools/youtube.png"
        subtitle: "Subscriptions"
        tag: "video"
        url: "https://www.youtube.com/feed/subscriptions"
      - name: "Twitch"
        logo: "assets/tools/twitch.png"
        subtitle: ""
        tag: "stream"
        url: "https://www.twitch.tv/"
      - name: "Amazon"
        logo: "assets/tools/amazon.png"
        subtitle: ""
        tag: "amazon"
        url: "https://smile.amazon.de/"
      - name: "PayPal"
        logo: "assets/tools/paypal.png"
        subtitle: "Dashboard"
        tag: "payment"
        url: "https://www.paypal.com/mep/dashboard"
  - name: "Network"
    icon: "fas fa-network-wired"
    items:
      - name: "AMP Panel"
        logo: "assets/tools/AMP_Icon_White_Lg_Blend.webp"
        subtitle: "(Only available on LAN)"
        tag: "gaming"
        url: "https://amp.local.meier.ninja/"
      - name: "Home Assistant"
        logo: "assets/tools/home-assistant.png"
        subtitle: ""
        tag: "smart-home"
        url: "https://home.meier.ninja/"
      - name: "UniFi UDR"
        logo: "assets/tools/ubiquiti.png"
        subtitle: "(Only available on LAN)"
        tag: "router"
        url: "https://192.168.2.1/"
  - name: "Kassensturz"
    icon: "fas fa-mobile-alt"
    items:
      - name: "Expo Builds"
        logo: "assets/tools/expo.png"
        subtitle: ""
        tag: "react-native"
        url: "https://expo.io/accounts/cceu_code-crafting_ug_haftungsbeschraenkt/projects/kassensturz-app/builds"
      - name: "Play Store Console"
        logo: "assets/tools/playstore.png"
        subtitle: "Android App Management"
        tag: "google"
        url: "https://play.google.com/console/u/6/developers/8696161505172713598/"
      - name: "App Store Connect"
        logo: "assets/tools/apple.png"
        subtitle: "iOS App Management"
        tag: "apple"
        url: "https://appstoreconnect.apple.com/"
